const parcels = [
  {
    id: '1',
    item: 'Electronics',
    fromUser: 'johndoe@gmail.com',
    toUser: 'lenalee@gmail.com',
    sendDate: '22-05-2021',
    deliveryDate: '23-05-2021',
    status: 'delivered',
    remarks: 'Received in good condition',
  },
  {
    id: '2',
    item: 'Accessories',
    fromUser: 'mosesdaa@gmail.com',
    toUser: 'johndoe@gmail.com',
    sendDate: '22-05-2021',
    deliveryDate: '23-05-2021',
    status: 'delivered',
    remarks: 'Received in good condition',
  },
  {
    id: '3',
    item: 'Foot wear',
    fromUser: 'lenalee@gmail.com',
    toUser: 'mosesdaa@gmail.com',
    sendDate: '22-05-2021',
    deliveryDate: '',
    status: 'pending',
    remarks: '',
  },
  {
    id: '4',
    item: 'Jamsuits',
    fromUser: 'johndoe@gmail.com',
    toUser: 'brucedee@gmail.com',
    sendDate: '22-05-2021',
    deliveryDate: '',
    status: 'pending',
    remarks: '',
  },
  {
    id: '5',
    item: 'Tablets',
    fromUser: 'johndoe@gmail.com',
    toUser: 'brucedee@gmail.com',
    sendDate: '22-05-2021',
    deliveryDate: '',
    status: 'pending',
    remarks: '',
  },
];

module.exports = parcels;
